"""Agent harnesses: the neutral skills render and the per-harness wiring (``onto agents``, ``onto setup --agent``).

**The neutral skills.** ``plugins/general-ontology/skills/`` stays the one source. ``render_skills`` turns it into
``.agents/skills/<name>/SKILL.md`` plus ``references/`` at the template root, which Devin, Codex, Cursor, GitHub
Copilot and Gemini CLI read (Claude Code keeps the plugin's own copy; ``.claude/skills/`` is never written, since
several harnesses read both folders and would load every skill twice). The render rules, in order:

- paragraphs between ``<!-- claude-only -->`` and ``<!-- /claude-only -->`` lines are dropped (the markers are HTML
  comments, so the Claude render never shows them);
- the frontmatter keeps only ``name`` and ``description``, and the description is cut at the last sentence end
  within ``DESCRIPTION_MAX`` characters;
- the sentence that defines ``O`` becomes ``O_SENTENCE``, and every other plugin-root path becomes the repo path;
- ``REWRITES`` turn the Claude Code only passages of today's sources (the question tool, the plugin install) into
  their plain-text form; a passage a later source marks ``claude-only`` is simply gone, and the rewrite then finds
  nothing to do;
- a header comment says the file is generated, from which source, and how to regenerate it.

A render that still holds a ``FORBIDDEN`` token is refused (``RenderError``), so a new Claude-only line in a source
fails ``onto agents render`` and the sync test instead of reaching another harness.

**The wiring.** ``HARNESSES`` lists what each harness reads, the files a topic gets for it (``files``) and the parts
set up in the harness's own app (``paste``). Every file is repo-relative and holds no absolute path or user name.
``plan_file`` merges a file into what is on disk: a JSON file keeps every other key (only the ``onto`` entries are
the kit's), a TOML file keeps every other table, and a file the user changed is never overwritten (``refused``),
unless its bytes are the ones setup itself wrote earlier. Deterministic: same input, same bytes.
"""

from __future__ import annotations

import json
import os
import re
from typing import Any, Dict, List, Optional, Sequence, Tuple

from . import __version__, util
from .commands import Context
from .errors import UsageError

KIT_REL = "plugins/general-ontology"
SOURCE_REL = KIT_REL + "/skills"
TARGET_REL = ".agents/skills"
ONTO = "python3 plugins/general-ontology/bin/onto"
REGENERATE = "python3 plugins/general-ontology/bin/onto agents render"
DESCRIPTION_MAX = 500
NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
CLAUDE_ONLY, CLAUDE_ONLY_END = "<!-- claude-only -->", "<!-- /claude-only -->"
GENERATED = "Generated by onto agents render"
# tokens no neutral render may hold: Claude Code's plugin variables, its question tool and its slash commands
FORBIDDEN = (("CLAUDE_PLUGIN_ROOT", re.compile(r"CLAUDE_PLUGIN_ROOT")),
             ("CLAUDE_PROJECT_DIR", re.compile(r"CLAUDE_PROJECT_DIR")),
             ("AskUserQuestion", re.compile(r"AskUserQuestion")),
             ("/plugin", re.compile(r"/plugin\b")),  # the slash command, not a plugins/ path
             ("--plugin-dir", re.compile(r"--plugin-dir")))
O_SENTENCE = ("`O` is `python3 plugins/general-ontology/bin/onto`, run from the topic repo root; prefer the `onto_*` "
              "MCP tools when this harness has them")
PLUGIN_ONTO = 'python3 "${CLAUDE_PLUGIN_ROOT}/bin/onto"'
EM_DASH = chr(0x2014)
JUNK_RE = re.compile(r"^.+ [0-9]+(\.[^. ]+)?$")  # Finder copies such as "stages 2.md"


class RenderError(UsageError):
    """A source the neutral render cannot take as it is (an unclosed marker, a token left for Claude Code only)."""


def _ws(phrase: str) -> str:
    """A regex for ``phrase`` that matches across any run of whitespace (the sources wrap at 120 columns)."""
    return r"\s+".join(re.escape(word) for word in phrase.split())


# (what to find, from its first words to its last, and what the neutral render says instead); each one matches
# across line breaks, at most once per file, and is skipped when the source no longer holds it
REWRITES: Tuple[Tuple[str, str, str], ...] = (
    # the router: its CLI line, in the one form every skill uses
    ("Prefer the `onto_*` MCP tools. When they are absent, use the CLI: `O` below is", PLUGIN_ONTO + "`",
     O_SENTENCE),
    # the other skills: "`O` is `...`; prefer the `onto_*` MCP tools"
    ("`O` is `" + PLUGIN_ONTO, "; prefer the `onto_*` MCP tools", O_SENTENCE),
    # the question tool is Claude Code's; everywhere else the options are numbered plain text
    ("use the question tool (AskUserQuestion", "list them as numbered plain-text options.",
     "list them as numbered plain-text options."),
    # a failed plugin install: the topic is ready, and its Next lines say how to open it
    ("the topic is ready, and its `Next:` lines open it with", "hand those over with the plugin step's detail.",
     "the topic is ready; hand its `Next:` lines over with the plugin step's detail."),
    # installing the Claude Code plugin by hand
    ("If the plugin step was skipped, or the user wants to install it by hand,",
     "that every topic on the machine loads its skills from.",
     "If the user wants the Claude Code plugin installed by hand, the README (Manual setup, step 2) says how."),
)


# the neutral skills ----------------------------------------------------------------------------------------------
def drop_claude_only(text: str, where: str = "") -> str:
    """``text`` without the lines from each ``<!-- claude-only -->`` line to its ``<!-- /claude-only -->`` line (both
    included); the blank lines around a dropped block fold into one. An unclosed or stray marker is refused."""
    out: List[str] = []
    inside = False
    for line in text.split("\n"):
        mark = line.strip()
        if mark == CLAUDE_ONLY:
            if inside:
                raise RenderError("%s: %s inside another claude-only block" % (where, CLAUDE_ONLY))
            inside = True
            continue
        if mark == CLAUDE_ONLY_END:
            if not inside:
                raise RenderError("%s: %s without its %s" % (where, CLAUDE_ONLY_END, CLAUDE_ONLY))
            inside = False
            continue
        if CLAUDE_ONLY in line or CLAUDE_ONLY_END in line:
            raise RenderError("%s: a claude-only marker must stand on a line of its own" % where)
        if not inside:
            out.append(line)
    if inside:
        raise RenderError("%s: %s is never closed (%s)" % (where, CLAUDE_ONLY, CLAUDE_ONLY_END))
    return re.sub(r"\n{3,}", "\n\n", "\n".join(out))


def cut_description(text: str, limit: int = DESCRIPTION_MAX) -> str:
    """``text`` on one line, cut after the last sentence end (``.``, ``!`` or ``?`` before a space or the end) that
    fits in ``limit`` characters; without one, after the last whole word that fits, with a period."""
    text = " ".join(str(text).split())
    if len(text) <= limit:
        return text
    best = 0
    for m in re.finditer(r"[.!?](?=\s|$)", text):
        if m.end() > limit:
            break
        best = m.end()
    if best:
        return text[:best]
    head = text[:limit].rsplit(" ", 1)[0].rstrip(",;:")
    return head[:limit - 1] + "."


def plain_scalar(value: str, where: str = "") -> str:
    """The text of a one-line YAML scalar: a "double quoted" or 'single quoted' value unquoted, a plain one as it
    is. A folded or literal block (``>``, ``|``) or a quote left open is refused, since the cut works on the text."""
    if value[:1] in (">", "|"):
        raise RenderError("%s: write the description on one line, not as a %s block" % (where, value[:1]))
    if value[:1] == '"':
        try:
            text = json.loads(value)
        except ValueError:
            text = None
        if not isinstance(text, str):
            raise RenderError("%s: the quoted description is not one closed \"...\" string" % where)
        return text
    if value[:1] == "'":
        if len(value) < 2 or not value.endswith("'") or "'" in value[1:-1].replace("''", ""):
            raise RenderError("%s: the quoted description is not one closed '...' string" % where)
        return value[1:-1].replace("''", "'")
    return value


def yaml_scalar(text: str, quoted: bool) -> str:
    """``text`` as a one-line YAML value: double quoted (JSON escapes, which YAML reads) when the source quoted it."""
    return json.dumps(text, ensure_ascii=False) if quoted else text


def split_frontmatter(text: str, where: str = "") -> Tuple[List[Tuple[str, str]], str]:
    """``([(key, value)], body)`` of a SKILL.md: ``key: value`` lines (a list item line belongs to the key above it
    and is dropped with it), then the body after the closing ``---``."""
    if not text.startswith("---\n"):
        raise RenderError("%s: a SKILL.md starts with a --- frontmatter block" % where)
    head, sep, body = text[4:].partition("\n---\n")
    if not sep:
        raise RenderError("%s: the frontmatter block is not closed" % where)
    pairs: List[Tuple[str, str]] = []
    for line in head.split("\n"):
        if not line.strip() or re.match(r"^\s+- ", line):
            continue
        m = re.match(r"^([a-z][a-z-]*):\s*(.*)$", line)
        if not m:
            raise RenderError("%s: unreadable frontmatter line %r" % (where, line))
        pairs.append((m.group(1), m.group(2).strip()))
    return pairs, body


# the span between a rewrite's first and last words: any text but a blank line, so a match stays in one paragraph
SPAN = r"(?:(?!\n[ \t]*\n)[\s\S])*?"


def neutral_body(text: str, where: str = "") -> str:
    """The body rules: the rewrites, then the plugin root as the repo path. A rewrite whose first words are there
    but whose last words are not in the same paragraph is refused: the source changed, and the rewrite would
    otherwise reach into the next paragraph or leave half a passage."""
    for first, last, instead in REWRITES:
        pattern = re.compile(_ws(first) + SPAN + _ws(last))
        text, count = pattern.subn(lambda _m: instead, text, count=1)
        if not count and re.search(_ws(first), text):
            raise RenderError("%s: the passage that starts %r no longer ends %r in the same paragraph; mark it %s "
                              "... %s in the source, or update REWRITES in ontokit/agents.py" % (
                                  where, first, last, CLAUDE_ONLY, CLAUDE_ONLY_END))
    text = text.replace(PLUGIN_ONTO, ONTO)
    return text.replace("${CLAUDE_PLUGIN_ROOT}", KIT_REL)


def header(source_rel: str) -> str:
    return "<!-- %s from %s; edit the source, then run %s -->\n" % (GENERATED, source_rel, REGENERATE)


def forbidden_in(text: str) -> List[str]:
    return [name for name, pattern in FORBIDDEN if pattern.search(text)]


def render_file(text: str, source_rel: str, skill: bool) -> str:
    """One neutral file from the source text (``skill``: a SKILL.md with frontmatter)."""
    text = drop_claude_only(text.replace("\r\n", "\n"), source_rel)
    if skill:
        pairs, body = split_frontmatter(text, source_rel)
        meta = dict(pairs)
        if not meta.get("name") or not meta.get("description"):
            raise RenderError("%s: the frontmatter needs name and description" % source_rel)
        description = yaml_scalar(cut_description(plain_scalar(meta["description"], source_rel)),
                                  meta["description"][:1] in "\"'")
        out = "---\nname: %s\ndescription: %s\n---\n%s%s" % (
            meta["name"], description, header(source_rel), neutral_body(body, source_rel))
    else:
        out = header(source_rel) + "\n" + neutral_body(text, source_rel)
    left = forbidden_in(out)
    if left:
        raise RenderError("%s: the neutral render still holds %s; mark that passage %s ... %s in the source, or add a "
                          "rewrite to ontokit/agents.py" % (source_rel, ", ".join(left), CLAUDE_ONLY, CLAUDE_ONLY_END))
    if EM_DASH in out:
        raise RenderError("%s: an em dash; use a colon, a comma or a full stop" % source_rel)
    return out


def _files_of(folder: str) -> List[str]:
    """The files under ``folder`` (relative, with /), sorted; hidden files, caches and Finder copies left out."""
    out = []
    for dirpath, dirs, files in os.walk(folder):
        dirs[:] = sorted(d for d in dirs if not d.startswith(".") and d != "__pycache__")
        for name in sorted(files):
            if name.startswith(".") or name.endswith(".pyc") or JUNK_RE.match(name):
                continue
            out.append(os.path.relpath(os.path.join(dirpath, name), folder).replace(os.sep, "/"))
    return sorted(out)


def skill_names(source: str) -> List[str]:
    if not os.path.isdir(source):
        return []
    return sorted(d for d in os.listdir(source) if os.path.isfile(os.path.join(source, d, "SKILL.md")))


def render_skills(source: str) -> Dict[str, bytes]:
    """``{path under .agents/skills: bytes}`` for every skill folder of ``source`` (``plugins/general-ontology/
    skills``): its SKILL.md and its references, Markdown rendered and any other file copied as it is."""
    out: Dict[str, bytes] = {}
    for name in skill_names(source):
        if not NAME_RE.match(name):
            raise RenderError("%s/%s: a skill name is lower case words joined by hyphens" % (SOURCE_REL, name))
        folder = os.path.join(source, name)
        for rel in _files_of(folder):
            path = os.path.join(folder, *rel.split("/"))
            with open(path, "rb") as fh:
                data = fh.read()
            key = "%s/%s" % (name, rel)
            if rel.endswith(".md"):
                text = render_file(data.decode("utf-8"), "%s/%s" % (SOURCE_REL, key), rel == "SKILL.md")
                if rel == "SKILL.md":
                    pairs, _body = split_frontmatter(text, key)
                    if dict(pairs).get("name") != name:
                        raise RenderError("%s/%s: the name in the frontmatter is not the folder name" % (
                            SOURCE_REL, key))
                data = text.encode("utf-8")
            out[key] = data
    return out


def _generated_folder(target: str, name: str) -> bool:
    """True when ``.agents/skills/<name>`` is one this render made (its SKILL.md carries the header)."""
    try:
        with open(os.path.join(target, name, "SKILL.md"), encoding="utf-8") as fh:
            return GENERATED in fh.read(4096)
    except (OSError, UnicodeDecodeError):
        return False


def skills_drift(root: str) -> Dict[str, Any]:
    """How ``<root>/.agents/skills`` differs from the render of ``<root>/plugins/general-ontology/skills``:
    ``{missing, changed, extra}`` (paths under ``.agents/skills``), with ``source`` False when there is no source.
    Only the kit's own skill folders count: one the user added there is never touched or reported."""
    source = os.path.join(root, *SOURCE_REL.split("/"))
    target = os.path.join(root, *TARGET_REL.split("/"))
    if not skill_names(source):
        return {"source": False, "missing": [], "changed": [], "extra": [], "files": 0}
    want = render_skills(source)
    owned = set(n.split("/", 1)[0] for n in want)
    if os.path.isdir(target):
        owned |= {d for d in os.listdir(target) if os.path.isdir(os.path.join(target, d)) and
                  _generated_folder(target, d)}
    have: Dict[str, bytes] = {}
    for name in sorted(owned):
        folder = os.path.join(target, name)
        if not os.path.isdir(folder):
            continue
        for rel in _files_of(folder):
            with open(os.path.join(folder, *rel.split("/")), "rb") as fh:
                have["%s/%s" % (name, rel)] = fh.read()
    return {"source": True, "files": len(want),
            "missing": sorted(k for k in want if k not in have),
            "changed": sorted(k for k in want if k in have and have[k] != want[k]),
            "extra": sorted(k for k in have if k not in want)}


def write_skills(root: str) -> Dict[str, Any]:
    """Write the render into ``<root>/.agents/skills``: changed and missing files written, the kit's stale files
    removed (and their folders, once empty). Returns ``{written, removed, unchanged}``."""
    drift = skills_drift(root)
    if not drift["source"]:
        raise UsageError("onto agents render: no skills at %s/%s (run it in a template checkout or a topic that "
                         "carries its kit)" % (root, SOURCE_REL))
    from . import store

    want = render_skills(os.path.join(root, *SOURCE_REL.split("/")))
    target = os.path.join(root, *TARGET_REL.split("/"))
    written = sorted(drift["missing"] + drift["changed"])
    for rel in written:
        path = os.path.join(target, *rel.split("/"))
        os.makedirs(os.path.dirname(path), exist_ok=True)
        store.write_bytes(path, want[rel])
    for rel in drift["extra"]:
        path = os.path.join(target, *rel.split("/"))
        os.remove(path)
        parent = os.path.dirname(path)
        while parent != target and os.path.isdir(parent) and not os.listdir(parent):
            os.rmdir(parent)
            parent = os.path.dirname(parent)
    return {"written": written, "removed": list(drift["extra"]), "unchanged": len(want) - len(written)}


# the harnesses ---------------------------------------------------------------------------------------------------
MCP_ARGS = "${workspaceFolder}/plugins/general-ontology/bin/onto-mcp"
HOOK = "plugins/general-ontology/bin/onto-session-start"
CODEX_MCP = ('T="$(git rev-parse --show-toplevel)" && exec python3 "$T/plugins/general-ontology/bin/onto-mcp" '
             '--repo "$T"')
WORKSPACE_SERVER = {"type": "stdio", "command": "python3", "args": [MCP_ARGS],
                    "env": {"ONTO_REPO": "${workspaceFolder}"}}
ASK = "Ask one question per message, as numbered plain-text options; always offer skip, later, n/a and why?"

BLUEPRINT = """\
# Devin reads this file from the default branch when the repo is added (written by onto setup --agent devin).
initialize:
  - name: Python 3.12
    uses: github.com/actions/setup-python@v5
    with:
      python-version: "3.12"
maintenance:
  - name: Check the onto kit
    run: python3 plugins/general-ontology/bin/onto doctor || true
knowledge:
  - name: onto
    contents: |
      Run `python3 plugins/general-ontology/bin/onto status` first, from the repo root, then follow AGENTS.md section 1.
      %s
      Every change to the ontology is a reviewed proposal.
      This machine is discarded after the session, with every unpushed commit: at stop, offer to push a session
      branch and open a PR, as plugins/general-ontology/docs/cloud-agents.md says.
""" % ASK

CURSOR_RULE = """\
---
description: How to work in this topic ontology repo (general-ontology kit)
alwaysApply: true
---
Follow AGENTS.md. At the start of each conversation, run `python3 plugins/general-ontology/bin/onto status` from the
repo root (or call the onto_status MCP tool) before anything else. %s The skills are in .agents/skills.
""" % ASK

CODEX_BLOCK = '[mcp_servers.onto]\ncommand = "sh"\nargs = ["-c", %s]\n' % json.dumps(CODEX_MCP)

DEVIN_MCP = """\
Devin web app: Customize, MCPs, Add custom MCP, transport STDIO. Optional: the CLI works without it. Fill in
the three fields:
Command: python3
Arguments: <repo>/plugins/general-ontology/bin/onto-mcp, --repo, <repo>
Environment Variables: none
<repo> is what pwd prints at the repo root in a Devin session; do not assume a home folder. Check it with Use MCP
in a session."""

DEVIN_PLAYBOOK = """\
Devin web app: Settings, Playbooks, Create playbook. Macro: !onto
## Overview
Run or continue the topic ontology interview in this repo with the general-ontology kit.
## What's Needed From User
- Answers to the interview questions, one at a time.
## Procedure
1. From the repo root, run `python3 plugins/general-ontology/bin/onto status`. When git branch -r lists an
   origin/onto/* session branch, ask whether to continue from it (plugins/general-ontology/docs/cloud-agents.md).
2. Follow AGENTS.md section 1 for that state, and use the skill it names with @skills:<name> (for example
   @skills:onto-interview).
3. %s Wait for the reply.
4. Record each answer the same turn, with the onto CLI or the onto_* MCP tools.
5. When the user says stop, write a checkpoint (`onto log --checkpoint`) and offer the commit. This machine is
   discarded after the session, so offer to push a new onto/<date> branch and open a PR with the proposals; a yes
   is the user asking for the push. Say the next session starts from the default branch: merge the PR first.
## Forbidden Actions
- Never merge a PR, push to the default branch or force-push.
- Never run a tool's invoke line without the user's yes for that run.
- Never put the user's words on a shell line; write them to a file under .onto/ first.
- Never run `onto init`. Never run `onto setup` where `onto doctor` says neither a topic nor a template checkout,
  and never `onto setup --new` without a remote to push the new topic to: the folder is lost with this machine.
- In a topic, never run setup except as AGENTS.md section 1 says:
  `onto setup --answers @.onto/setup.json --launch none` with the flags the answers map to, and no --new or --here.""" % ASK

DEVIN_GAPS = """\
Optional. Devin web app: Settings, Playbooks, Create playbook. Macro: !onto-gaps
## Overview
Turn the topic's open gaps into issue drafts.
## Procedure
1. From the repo root, run `python3 plugins/general-ontology/bin/onto gaps`.
2. Draft one issue per gap the user picks, with the question that closes it.
3. Create each issue only with the user's yes for it.
## Forbidden Actions
- Never create an issue without the user's yes.
- Never change the ontology from this playbook."""

COPILOT_CLOUD = """\
GitHub: the repo's Settings, Copilot, MCP servers (the cloud agent's MCP configuration). Paste:
{"mcpServers": {"onto": {"type": "local", "command": "python3",
  "args": ["plugins/general-ontology/bin/onto-mcp", "--repo", "."], "tools": ["*"]}}}
Unverified: whether the cloud agent starts it at the checkout root."""

GENERIC_MCP = """\
Any agent with stdio MCP support, set up by hand in its own settings:
command: python3
args: <repo>/plugins/general-ontology/bin/onto-mcp --repo <repo>
(or set ONTO_REPO=<repo> in the server's environment). <repo> is the topic repo root.
Without MCP: run python3 plugins/general-ontology/bin/onto status from the repo root, then follow AGENTS.md."""

# harnesses that read AGENTS.md natively and get no files: the "generic" setup (as of 2026-10-06)
OTHERS: Tuple[Tuple[str, str, str], ...] = (
    ("OpenCode", "AGENTS.md and .agents/skills", "the mcp entry of opencode.json"),
    ("Amp", "AGENTS.md", ".amp/settings.json, then amp mcp approve onto"),
    ("goose", "AGENTS.md (its default context files)", "a stdio extension in its own config"),
    ("Zed", "the first of its rules files it finds, AGENTS.md among them", "context_servers in the user settings"),
    ("Jules", "AGENTS.md", "custom stdio MCP unverified: use the CLI"),
    ("Factory", "AGENTS.md (unverified)", ".factory/mcp.json (unverified)"),
    ("Aider", "AGENTS.md only when .aider.conf.yml lists it under read:", "no MCP: the CLI only"),
)


def _key(path: Sequence[str], value: Any) -> Dict[str, Any]:
    return {"kind": "key", "path": list(path), "value": value}


def _member(path: Sequence[str], value: Any, marker: str) -> Dict[str, Any]:
    return {"kind": "member", "path": list(path), "value": value, "marker": marker}


def _hook_group(matcher: str, command: str, timeout: Optional[int] = None) -> Dict[str, Any]:
    hook: Dict[str, Any] = {"type": "command", "command": command}
    if timeout is not None:
        hook["timeout"] = timeout
    return {"matcher": matcher, "hooks": [hook]}


HARNESSES: Tuple[Dict[str, Any], ...] = (
    {"name": "claude", "label": "Claude Code",
     "reads": ["CLAUDE.md, which imports AGENTS.md",
               "the general-ontology plugin (its skills, MCP server and session-start hook), wired in "
               ".claude/settings.json by the plugin step"],
     "files": [], "paste": [],
     "open": "Open it in Claude Code (terminal `claude`, or the desktop app's Code tab) and say: start the ontology",
     "notes": ["The plugin step of onto setup wires it (--plugin project, local, plugin-dir or skip)."]},
    {"name": "devin", "label": "Devin",
     "reads": ["AGENTS.md (the first 16 KiB)", ".agents/skills (use @skills:<name>)",
               ".devin/blueprint.yaml (from the default branch, when the repo is added or synced)",
               ".devin/hooks.v1.json (the Devin CLI and Devin Local only)",
               "MCP servers and playbooks set in the web app (paste blocks)"],
     "files": [
         {"path": ".devin/blueprint.yaml", "format": "text", "text": BLUEPRINT},
         {"path": ".devin/hooks.v1.json", "format": "json", "parts": [
             _member(["SessionStart"], _hook_group("", "python3 %s --format json" % HOOK, 10), HOOK)]}],
     "paste": [{"title": "Devin MCP server", "text": DEVIN_MCP},
               {"title": "Devin playbook !onto", "text": DEVIN_PLAYBOOK},
               {"title": "Devin playbook !onto-gaps (optional)", "text": DEVIN_GAPS}],
     "open": "Devin: add the repo in Devin's settings (Devin clones it from your git host), paste the blocks "
             "below, then start a session with !onto, or say: start the ontology",
     "needs_origin": "Devin clones the topic from a git host, and it has no remote yet: create a private repo "
                     "there, then run git -C %s remote add origin <url> && git -C %s push -u origin main",
     "notes": ["The maintenance step runs at build time, not at session start.",
               "The hooks file is read by the Devin CLI and Devin Local only; whether cloud sessions run "
               "SessionStart hooks is unverified, so cloud Devin starts from AGENTS.md.",
               "Its command needs onto-session-start --format json (kit 0.3.0).",
               "A cloud session's machine is discarded after it: work not pushed is lost, and the next session "
               "clones the default branch (plugins/general-ontology/docs/cloud-agents.md)."]},
    {"name": "codex", "label": "Codex",
     "reads": ["AGENTS.md (up to 32 KiB)", ".agents/skills",
               ".codex/config.toml and .codex/hooks.json (in a trusted project only)"],
     "files": [
         {"path": ".codex/config.toml", "format": "toml", "table": "mcp_servers.onto", "text": CODEX_BLOCK},
         {"path": ".codex/hooks.json", "format": "json", "parts": [
             _member(["hooks", "SessionStart"], _hook_group(
                 "startup|resume|clear|compact",
                 'python3 "$(git rev-parse --show-toplevel)/%s"' % HOOK), HOOK)]}],
     "paste": [],
     "open": "Codex: run codex in the folder and trust the project when it asks (the .codex files need it), then "
             "say: start the ontology",
     "notes": ["Codex reads .codex/ only in a trusted project: accept its trust prompt, or add "
               "[projects.\"<repo>\"] trust_level = \"trusted\" to your own ~/.codex/config.toml yourself. Setup "
               "never edits ~/.codex.",
               "The MCP server and the hook find the repo root with git rev-parse; that Codex runs a hook command "
               "through a shell is unverified."]},
    {"name": "cursor", "label": "Cursor",
     "reads": ["AGENTS.md", ".agents/skills", ".cursor/mcp.json", ".cursor/rules/*.mdc"],
     "files": [
         {"path": ".cursor/mcp.json", "format": "json", "parts": [_key(["mcpServers", "onto"], WORKSPACE_SERVER)]},
         {"path": ".cursor/rules/onto.mdc", "format": "text", "text": CURSOR_RULE}],
     "paste": [],
     "open": "Cursor: open the folder in Cursor, approve the onto MCP server, then say: start the ontology",
     "notes": ["Cloud agents run no session-start hook; the rule and AGENTS.md say to run onto status first."]},
    {"name": "copilot", "label": "GitHub Copilot",
     "reads": ["AGENTS.md", ".agents/skills", ".vscode/mcp.json (VS Code)",
               "the cloud agent's MCP settings on GitHub (paste block)"],
     "files": [
         {"path": ".vscode/mcp.json", "format": "json", "parts": [_key(["servers", "onto"], WORKSPACE_SERVER)]}],
     "paste": [{"title": "Copilot cloud agent MCP", "text": COPILOT_CLOUD}],
     "open": "Copilot: open the folder in VS Code, trust it and start the onto MCP server, then ask Copilot in "
             "agent mode: start the ontology",
     "notes": ["VS Code reads AGENTS.md while chat.useAgentsMdFile is on."]},
    {"name": "gemini", "label": "Gemini CLI",
     "reads": ["AGENTS.md (only because .gemini/settings.json lists it in context.fileName)", ".agents/skills",
               ".gemini/settings.json"],
     "files": [
         {"path": ".gemini/settings.json", "format": "json", "parts": [
             _member(["context", "fileName"], "AGENTS.md", "AGENTS.md"),
             _key(["mcpServers", "onto"], {"command": "python3", "args": [
                 "plugins/general-ontology/bin/onto-mcp", "--repo", "."], "cwd": "."})]}],
     "paste": [],
     "open": "Gemini CLI: run gemini in the folder (trust it when asked), then say: start the ontology",
     "notes": ["Without context.fileName, Gemini CLI reads GEMINI.md only."]},
    {"name": "generic", "label": "another agent",
     "reads": ["AGENTS.md", ".agents/skills, when the agent reads that folder",
               "the MCP command below, set up by hand"],
     "files": [], "paste": [{"title": "MCP for any other agent", "text": GENERIC_MCP}],
     "open": "Another agent: open the folder and ask the agent to follow AGENTS.md",
     "notes": ["%s: reads %s; MCP: %s." % row for row in OTHERS]},
)
NAMES = tuple(h["name"] for h in HARNESSES)
_BY_NAME = {h["name"]: h for h in HARNESSES}
WIRED_PATHS = tuple(sorted(f["path"] for h in HARNESSES for f in h["files"]))


def harness(name: str) -> Dict[str, Any]:
    found = _BY_NAME.get(str(name or "").strip().lower())
    if found is None:
        raise UsageError("unknown agent %r; one of %s" % (name, ", ".join(NAMES)), accepted=list(NAMES))
    return found


def parse_agents(value: Any) -> List[str]:
    """A list of harness names (``claude,devin`` or a list), checked, without repeats, in ``NAMES`` order."""
    items: List[str] = []
    for item in (value if isinstance(value, (list, tuple)) else [value]):
        items.extend(p.strip().lower() for p in str(item or "").split(",") if p.strip())
    unknown = sorted({i for i in items if i not in _BY_NAME})
    if unknown:
        raise UsageError("--agent: unknown agent %s; one of %s" % (", ".join(unknown), ", ".join(NAMES)))
    return [n for n in NAMES if n in items]


# merging one file -----------------------------------------------------------------------------------------------
def _dump_json(doc: Any) -> bytes:
    return (json.dumps(doc, indent=2, ensure_ascii=False) + "\n").encode("utf-8")


def _container(doc: Dict[str, Any], path: List[str], create: bool) -> Tuple[Optional[Dict[str, Any]], str]:
    """The object holding ``path[-1]`` (made on the way when ``create``), or (None, why)."""
    node: Any = doc
    for i, key in enumerate(path[:-1]):
        child = node.get(key)
        if child is None:
            if not create:
                return None, ""
            child = node[key] = {}
        if not isinstance(child, dict):
            return None, "%s is not an object" % ".".join(path[:i + 1])
        node = child
    return node, ""


def _merge_json(spec: Dict[str, Any], current: Optional[bytes], own: bool) -> Tuple[str, Optional[bytes], str]:
    if current is None:
        doc: Dict[str, Any] = {}
    else:
        try:
            doc = json.loads(current.decode("utf-8"))
        except (ValueError, UnicodeDecodeError) as exc:
            return "refused", None, "it is not valid JSON (%s)" % exc
        if not isinstance(doc, dict):
            return "refused", None, "it is not a JSON object"
    changed = False
    for part in spec["parts"]:
        path, value = part["path"], json.loads(json.dumps(part["value"]))  # a copy: the spec stays as it is
        node, why = _container(doc, path, True)
        if node is None:
            return "refused", None, why
        last = path[-1]
        if part["kind"] == "key":
            if last in node and node[last] == value:
                continue
            if last in node and not own:
                return "refused", None, "%s holds another entry" % ".".join(path)
            node[last] = value
            changed = True
            continue
        have = node.get(last)
        if have is None:
            items: List[Any] = []
        elif isinstance(have, list):
            items = list(have)
        elif isinstance(have, str):
            items = [have]
        else:
            return "refused", None, "%s is not a list" % ".".join(path)
        if value in items:
            continue
        ours = [i for i, item in enumerate(items) if part["marker"] in json.dumps(item, ensure_ascii=False)]
        if ours and not own:
            return "refused", None, "%s holds another onto entry" % ".".join(path)
        for i in reversed(ours):
            del items[i]
        items.append(value)
        node[last] = items
        changed = True
    if not changed:
        return "already", current, ""
    return "write", _dump_json(doc), ""


TABLE_RE = re.compile(r"^\s*\[\[?[^\]\n]+\]\]?\s*(#.*)?$")


def _toml_key(key: str) -> str:
    """A regex for one bare TOML key part as written bare, "double quoted" or 'single quoted'."""
    k = re.escape(key)
    return r"(?:%s|\"%s\"|'%s')" % (k, k, k)


def _merge_toml(spec: Dict[str, Any], current: Optional[bytes], own: bool) -> Tuple[str, Optional[bytes], str]:
    block = spec["text"]
    if current is None:
        return "write", block.encode("utf-8"), ""
    try:
        text = current.decode("utf-8")
    except UnicodeDecodeError:
        return "refused", None, "it is not UTF-8 text"
    lines = text.split("\n")
    parts = spec["table"].split(".")
    head = re.compile(r"^\s*\[\s*%s\s*\]\s*(#.*)?$" % r"\s*\.\s*".join(_toml_key(k) for k in parts))
    start = next((i for i, line in enumerate(lines) if head.match(line)), None)
    if start is None:
        top = _toml_key(parts[0])
        if re.search(r"(?m)^\s*\[\s*%s\s*\]" % top, text) or re.search(r"(?m)^\s*%s\s*[.=]" % top, text):
            return "refused", None, "it sets %s another way; add the [%s] table by hand" % (parts[0], spec["table"])
        if not text.strip():
            return "write", block.encode("utf-8"), ""
        body = text.rstrip("\n") + "\n\n"  # one blank line between the user's tables and the kit's
        return "write", (body + block).encode("utf-8"), ""
    end = next((i for i in range(start + 1, len(lines)) if TABLE_RE.match(lines[i])), len(lines))
    # the table's body, not its header line: [mcp_servers."onto"] is the same table as [mcp_servers.onto]
    have = "\n".join(lines[start + 1:end]).strip()
    if have == block.strip().split("\n", 1)[1].strip():
        return "already", current, ""
    if not own:
        return "refused", None, "its [%s] table differs" % spec["table"]
    rest = lines[end:]
    new = "\n".join(lines[:start] + block.rstrip("\n").split("\n") + ([""] + rest if rest else [""]))
    return "write", new.encode("utf-8"), ""


def plan_file(spec: Dict[str, Any], current: Optional[bytes], own: bool = False) -> Tuple[str, Optional[bytes], str]:
    """(``already`` | ``write`` | ``refused``, the bytes to write or keep, why refused) for one harness file over
    ``current`` (None when absent). ``own``: these bytes are the ones setup wrote earlier, so the kit's parts may
    change; otherwise a file whose kit part differs is the user's and is refused."""
    fmt = spec["format"]
    if fmt == "json":
        return _merge_json(spec, current, own)
    if fmt == "toml":
        return _merge_toml(spec, current, own)
    data = spec["text"].encode("utf-8")
    if current is None or (own and current != data):
        return "write", data, ""
    if current == data:
        return "already", current, ""
    return "refused", None, "it differs from the kit's"


def fresh(spec: Dict[str, Any]) -> bytes:
    """The bytes of ``spec`` written into an empty repo."""
    _status, data, _why = plan_file(spec, None)
    assert data is not None
    return data


def _read(root: str, rel: str) -> Optional[bytes]:
    path = os.path.join(root, *rel.split("/"))
    if not os.path.isfile(path):
        return None
    try:
        with open(path, "rb") as fh:
            return fh.read()
    except OSError:
        return None


def file_states(root: str, name: str) -> List[Dict[str, str]]:
    """``[{path, state}]`` for each file of harness ``name`` in ``root``: ``absent``, ``ok`` (the kit's parts are
    there, as rendered) or ``differs`` (missing or different kit parts, or unreadable)."""
    out = []
    for spec in harness(name)["files"]:
        current = _read(root, spec["path"])
        if current is None:
            out.append({"path": spec["path"], "state": "absent"})
            continue
        status, _data, _why = plan_file(spec, current)
        out.append({"path": spec["path"], "state": "ok" if status == "already" else "differs"})
    return out


def wired(root: str, name: str) -> str:
    """``wired``, ``partly``, ``differs``, ``not wired`` or ``no files`` for harness ``name`` in ``root``."""
    if name == "claude":
        from . import doctor

        wiring = doctor.settings_wiring(root)
        return "wired" if (wiring.get("project") or wiring.get("local")) else "not wired"
    states = [s["state"] for s in file_states(root, name)]
    if not states:
        return "no files"
    if all(s == "absent" for s in states):
        return "not wired"
    if "differs" in states:
        return "differs"
    return "wired" if all(s == "ok" for s in states) else "partly"


def apply(root: str, name: str, own: Dict[str, str]) -> List[Dict[str, Any]]:
    """Write the files of harness ``name`` into ``root``. ``own`` maps a path to the sha256 of the bytes setup wrote
    there earlier. Returns ``[{path, status (done | already | refused), detail, sha}]``."""
    from . import store

    out = []
    for spec in harness(name)["files"]:
        rel = spec["path"]
        current = _read(root, rel)
        mine = current is not None and own.get(rel) == util.sha256_hex(current)
        status, data, why = plan_file(spec, current, mine)
        item: Dict[str, Any] = {"path": rel, "status": status, "detail": why, "sha": None}
        if status == "write" and data is not None:
            path = os.path.join(root, *rel.split("/"))
            os.makedirs(os.path.dirname(path), exist_ok=True)
            store.write_bytes(path, data)
            item["status"], item["sha"] = "done", util.sha256_hex(data)
        elif status == "already" and current is not None:
            item["sha"] = util.sha256_hex(current)
        out.append(item)
    return out


def paste_blocks(names: Sequence[str]) -> List[Dict[str, str]]:
    return [{"agent": n, "title": block["title"], "text": block["text"]} for n in names
            for block in harness(n)["paste"]]


def skills_check(root: str) -> Dict[str, Any]:
    """The doctor's ``agents`` check: ``.agents/skills`` equals the render of this kit's skills, and every wired
    harness file holds the kit's parts as rendered."""
    from .doctor import check

    problems: List[str] = []
    fixes: List[str] = []
    try:
        drift = skills_drift(root)
    except (RenderError, OSError, UnicodeDecodeError) as exc:
        drift = {"source": True, "missing": [], "changed": [], "extra": [], "error": str(exc)}
    if drift.get("error"):
        problems.append("the skills do not render: %s" % drift["error"])
    elif drift["source"]:
        bad = drift["missing"] + drift["changed"] + drift["extra"]
        if bad:
            shown = ", ".join(bad[:3]) + (", ..." if len(bad) > 3 else "")
            problems.append(".agents/skills differs from the render of kit %s (%d file%s: %s)" % (
                __version__, len(bad), "" if len(bad) == 1 else "s", shown))
            fixes.append("in the template, run %s and commit it; in a topic, take .agents/ from the kit "
                         "(git checkout kit/general-ontology -- .agents)" % REGENERATE)
    names = []
    for h in HARNESSES:
        if not h["files"]:
            continue
        state = wired(root, h["name"])
        if state in ("wired",):
            names.append(h["name"])
        elif state in ("differs", "partly"):
            names.append(h["name"])
            states = file_states(root, h["name"])
            odd = [s["path"] for s in states if s["state"] != "ok"]
            changed = [s["path"] for s in states if s["state"] == "differs"]
            problems.append("%s: %s %s its render" % (h["name"], ", ".join(odd), "differ from" if len(odd) > 1
                                                      else "differs from"))
            if changed:
                # setup never overwrites a file it did not write, so it cannot repair these: name the real repair
                fixes.append("merge the kit's entries into %s by hand (onto agents show %s prints them), or move "
                             "%s aside and run onto setup --agent %s" % (
                                 ", ".join(changed), h["name"], "them" if len(changed) > 1 else "it", h["name"]))
            else:
                fixes.append("onto setup --agent %s" % h["name"])
    if problems:
        return check("agents", "warn", "; ".join(problems), "; ".join(fixes))
    parts = [".agents/skills matches the render of kit %s" % __version__ if drift["source"] else
             "no skills to render in this kit"]
    parts.append("wired: %s" % ", ".join(names) if names else "no agent files")
    return check("agents", "ok", "; ".join(parts))


# onto agents -----------------------------------------------------------------------------------------------------
def _root(ctx: Context) -> Tuple[str, str]:
    from . import doctor

    start = os.path.abspath(os.path.expanduser(ctx.explicit or ctx.cwd or os.getcwd()))
    return doctor.locate(start, ctx.env, ctx.explicit)


def _quiet_stamp(ctx: Context, where: str, root: str) -> None:
    """The version line names the folder these results are about, never a topic ``$ONTO_REPO`` points at."""
    from . import store
    from .errors import OntoError

    ctx.env.pop("ONTO_REPO", None)
    found = None
    if where == "topic":
        try:
            found = store.Repo.open(root)
        except OntoError:
            found = None
    ctx.repo = found
    if found is None:
        ctx.explicit, ctx.cwd = None, os.path.abspath(os.sep)


def show(name: str) -> Dict[str, Any]:
    h = harness(name)
    return {"agent": h["name"], "label": h["label"], "reads": list(h["reads"]),
            "files": [{"path": f["path"], "content": fresh(f).decode("utf-8")} for f in h["files"]],
            "paste": paste_blocks([h["name"]]), "open": h["open"], "notes": list(h["notes"])}


def cmd_agents(ctx: Context, args: Dict[str, Any]) -> Dict[str, Any]:
    action = args.get("action") or "list"
    if action == "show":
        if not args.get("name"):
            raise UsageError("onto agents show needs a name: one of %s" % ", ".join(NAMES), accepted=list(NAMES))
        result = {"action": "show"}
        result.update(show(args["name"]))
        where, root = _root(ctx)
        _quiet_stamp(ctx, where, root)
        return result
    if args.get("name"):
        raise UsageError("onto agents %s takes no name (only show does)" % action)
    where, root = _root(ctx)
    _quiet_stamp(ctx, where, root)
    if action == "list":
        rows = []
        for h in HARNESSES:
            rows.append({"name": h["name"], "label": h["label"], "reads": list(h["reads"]),
                         "files": [f["path"] for f in h["files"]], "paste": bool(h["paste"]),
                         "wired": wired(root, h["name"]) if where in ("topic", "template") else "not checked"})
        return {"action": "list", "where": where, "root": root, "agents": rows}
    if action != "render":
        raise UsageError("onto agents: list, show <name> or render [--check]")
    if where not in ("topic", "template"):
        raise UsageError("onto agents render: run it in a template checkout (or a topic that carries its kit): %s is "
                         "neither" % root)
    if args.get("check"):
        drift = skills_drift(root)
        if not drift["source"]:
            raise UsageError("onto agents render --check: no skills at %s/%s" % (root, SOURCE_REL))
        bad = drift["missing"] + drift["changed"] + drift["extra"]
        return {"action": "render", "check": True, "root": root, "files": drift["files"],
                "missing": drift["missing"], "changed": drift["changed"], "extra": drift["extra"],
                "exit_code": 1 if bad else 0}
    done = write_skills(root)
    result = {"action": "render", "check": False, "root": root}
    result.update(done)
    return result


def render_agents(result: Dict[str, Any], mode: str, ctx: Context) -> List[str]:
    from .onboard import one_line

    action = result.get("action")
    if action == "list":
        lines = ["agents at %s (%s)" % (one_line(result.get("root")), result.get("where"))]
        for row in result.get("agents") or []:
            lines.append("%-8s %-15s %s" % (row["name"], row["wired"], row["label"]))
            lines.append("         reads: %s" % "; ".join(row["reads"]))
            if row["files"]:
                lines.append("         files: %s" % ", ".join(row["files"]))
        lines.append("Details: onto agents show <name>; wire one: onto setup --agent <name>")
        return lines
    if action == "show":
        lines = ["%s (%s)" % (result.get("label"), result.get("agent")), "Reads:"]
        lines += ["  %s" % r for r in result.get("reads") or []]
        for f in result.get("files") or []:
            lines.append("File %s:" % f["path"])
            lines += ["  %s" % line for line in f["content"].rstrip("\n").split("\n")]
        if not result.get("files"):
            lines.append("Files: none")
        for block in result.get("paste") or []:
            lines.append("Paste, %s:" % block["title"])
            lines += ["  %s" % line for line in block["text"].split("\n")]
        lines.append("Open: %s" % result.get("open"))
        lines += ["Note: %s" % n for n in result.get("notes") or []]
        return lines
    if result.get("check"):
        bad = [("missing", result.get("missing") or []), ("changed", result.get("changed") or []),
               ("not in the render", result.get("extra") or [])]
        if not any(paths for _what, paths in bad):
            return [".agents/skills matches the render (%d files)" % (result.get("files") or 0)]
        lines = [".agents/skills differs from the render of %s:" % SOURCE_REL]
        for what, paths in bad:
            lines += ["  %s: %s" % (what, p) for p in paths]
        lines.append("Regenerate it: %s" % REGENERATE)
        return lines
    written, removed = result.get("written") or [], result.get("removed") or []
    lines = [".agents/skills: %d written, %d removed, %d unchanged" % (
        len(written), len(removed), result.get("unchanged") or 0)]
    lines += ["  wrote %s" % p for p in written] + ["  removed %s" % p for p in removed]
    return lines
